name: YAML to ENV
description: |
  Parse all keys & values out of a YAML file, adding them to the $GITHUB_ENV file

branding:
  icon: copy
  color: blue

inputs:
  yaml-file:
    required: true
    description: "Filepath to YAML to parse"
  yq-version:
    required: false
    description: "Version of yq to install, if not already in path.  Tested with >= 4.25."
  mask-values:
    required: false
    default: "false"
    description: "Add value masking to all exported environment variable values (https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#example-masking-an-environment-variable)"

outputs:
  yq-installed:
    description: "'true' if yq was installed by this action"
    value: "${{ steps.install-yq.outputs.installed == 'false' }}"
  var-count:
    description: "Number of environment variables defined from source YAML file."
    value: "${{ steps.y2e.outputs.var-count }}"
  yaml-keys:
    description: "Comma-separated string of keys extracted from source YAML file."
    value: "${{ steps.y2e.outputs.yaml-keys }}"
  env-names:
    description: "Comma-separated string of exported environment variable names"
    value: "${{ steps.y2e.outputs.env-names }}"

runs:
  using: composite
  steps:
    - name: Check yaml file existence
      shell: bash
      run: |
        if ! [ -f '${{ inputs.yaml-file }}' ]; then
          echo 'Configured YAML file "${{ inputs.yaml-file }}" not found'
          exit 1
        fi

    - name: 'Install yq (${{ inputs.yq-version }})'
      id: install-yq
      uses: dcarbone/install-yq-action@v1.3.1
      with:
        version: '${{ inputs.yq-version }}'

    - name: YAML to ENV
      id: y2e
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/yaml-to-env.sh
      env:
        YAMLTOENV_MASK_VALUES: '${{ inputs.mask-values }}'
        YAMLTOENV_YAML_FILE: '${{ inputs.yaml-file }}'
